plugins {
    id 'java'
    id 'application'
}

group = 'com.rbac'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

application {
    mainClass = 'Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'Main'
    }
}